packaging_format = 2

id = "gitlab"
name = "GitLab"
description.en = "Git-repository manager providing wiki, issue-tracking and CI/CD pipeline features"
description.fr = "Gestionnaire de dépôts Git proposant des fonctionnalités de wiki, suivi de bugs et de pipeline CI/CD"

version = "15.9.1~ynh1"

maintainers = ["kay0u"]

[upstream]
license = "MIT"
website = "https://gitlab.com"
demo = "https://gitlab.com/explore"
admindoc = "https://docs.gitlab.com/"
code = "https://gitlab.com/gitlab-org/omnibus-gitlab - https://gitlab.com/gitlab-org/gitlab"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.2.3"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = false
ldap = true
sso = false
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/gitlab"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.init_main_permission]
    help.en = "If your GitLab instance is public, anyone can see your public repositories."
    help.fr = "Si votre instance GitLab est publique, tout le monde pourra voir vos dépôts publics."
    type = "group"
    default = "visitors"

    [install.use_web_account]
    ask.en = "Authorize account creation from GitLab web interface"
    ask.fr = "Autoriser la création de compte depuis l'interface web de GitLab ?"
    type = "boolean"
    default = false

[resources]
    [resources.system_user]

    [resources.install_dir]
    dir = "/opt/__APP__"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8080
    puma.default = 8081
    sidekiq.default = 8082

    [resources.apt]
    packages = "openssh-server"
