test_format = 1.0

[default]
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.7b4758b323155c5b31287250dbe696cdf295a52c.name = "Upgrade from 16.1.1"