test_format = 1.0

[default]
    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.722fa8db9d8d840064ffc64338e1170da7cafc37.name = "Upgrade from 15.0.0"